### ISSUE TITLE
Removal of Spanish translation repository

### ISSUE THREAD

**Issue by JoseDeFreitas** [mbiesiad/awesome-translations#35]
Hello. I'm the one who translated the content of this repository into Spanish (see PR #10); for personal reasons, I deleted the fork I made where I translated the content. The [Spanish link in the Translations section](https://github.com/mbiesiad/awesome-translations#translations) now points to a 404 page, so I wanted to make you know about this. Nonetheless, I saved the translation in web.archive.org, if you want to keep it and upload it in another branch in this repository, for example ([link here](https://web.archive.org/web/20220511155347/https://github.com/JoseDeFreitas/awesome-translations/tree/es_ES)). Sorry for the inconvenient.

**Comment by mbiesiad** [comment]
Hello @JoseDeFreitas Sure, I remember you! That was a pleasure for me. Thank you so much for your help & message here.

I will take care of it. Best wishes

**Comment by mbiesiad** [comment]
Updated. 🎉 Once again, thank you so much for your contributions here! ✨

**Comment by JoseDeFreitas** [comment]
Hello, @mbiesiad. I didn't think of adding the link to the web.archive.org page, great idea! Thank you and good luck with everything :smile:.
