### ISSUE TITLE
Add GILT Forum - Globalization Strategy playbook

### ISSUE THREAD

**Issue by alexture** [mbiesiad/awesome-translations#42]
Hiya! I really like this resource: https://github.com/GILT-Forum/Globalization-Strategy-Playbook and feel like it should be added. Unfortunately my skillset does _not_ include pull requests, so I'm adding an issue here hoping someone figures it out for me! :)

**Comment by mbiesiad** [comment]
Hi @alexture I would be happy to help. Agree. Definitely! 🚀 Thank you so much for you contribution here! Added 🎉

Have a great day, best wishes!

**Comment by alexture** [comment]
Thanks so much!

**Comment by mbiesiad** [comment]
My pleasure! ✨
