### ISSUE TITLE
Organisation question: by doc type or by topic?

### ISSUE THREAD

**Issue by alexture** [mbiesiad/awesome-translations#49]
Hello!

Currently, we have the following sections for tools & documentation: 

* Tools
* Articles
* Blogs
* Online courses
* Books
* Other

So the grouping is done by documentation type. I feel like grouping by topic would be more useful, eg.

* Introductions to i18n
* For developers
    * General tools
    * Python
        * Online courses about i18n in Python
        * Python library dedicated to i18n
    * etc.
* For translators
    * Tools
    * CAT tools
    * General online courses
* For end users
    * Browser extensions with machine translation

What do you think? :)

**Comment by alexture** [comment]
Oh please please take your time! We're volunteers, please no pressure ever on my behalf :)

**Comment by mbiesiad** [comment]
Hi, really sorry for delay and thank you very much for your patience, time and effort once again! ❤ I agree with you, sounds great. Some of changes (improvements!) were actually already implemented thanks to your contributions! 🚀 Have a great day, best wishes!

**Comment by mbiesiad** [comment]
Every software, idea, and so on has own "lifecycle" and it's good to be open to changes, improvements in my opinion ✨

**Comment by alexture** [comment]
Will restructure by topic then, thanks for being so open!
