### ISSUE TITLE
Spanish translation request

### ISSUE THREAD

**Issue by JoseDeFreitas** [mbiesiad/awesome-translations#9]
Hello!
I came to this project and really liked it. I saw there's a branch for Polish, making me think you might want branches for every language. I would want to translate this into Spanish. I'm a native Spanish speaker that has previously worked in translations from English to Spanish in other open-source projects. Tell me if I can start working on it.
If this is not the case, just close this issue.
Thank you in advance.

**Comment by mbiesiad** [comment]
Hi @JoseDeFreitas Thanks you so much for your feedback & the kind words. Nice to meet you. 🔥 I'm glad to hear this.

Your idea is great, it would be lovely! 🚀 Sure, please feel free. Let's keep in touch.

Best wishes,

**Comment by JoseDeFreitas** [comment]
Hello Michal 👋. Just created the pull request I mentioned. Thank you for allowing me to work on the translation 👍.

**Comment by mbiesiad** [comment]
Hello @JoseDeFreitas  once again, thanks a lot for your effort here! That's awesome!! 🔥 My pleasure! ⭐

**Comment by mbiesiad** [comment]
May I close the issue?

**Comment by JoseDeFreitas** [comment]
Hello Michal! Yes. The translation has already been made 👌.
